# $GITHUB_WORKSPACE/src -> this project files
# $GITHUB_WORKSPACE/grpc_defs -> proto files
# $GITHUB_WORKSPACE/tools -> tools for code generation
name: SDK Generation
on: repository_dispatch
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out project files
        uses: actions/checkout@v1
        with:
          path: src
      - name: Check out proto files
        uses: actions/checkout@v1
        with:
          repository: QuorumEngineering/quorum-plugin-definitions
          ref: refs/heads/simple
          token: ${{ secrets.QUORUMBOT_PAT }}
          path: grpc_defs
      - name: Install protoc compiler and tools
        run: |
          mkdir -p ../tools && cd ../tools
          curl -sS -L https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip -o protoc.zip && unzip -q protoc.zip
          echo "protoc version: " && ./bin/protoc --version
          export GOPATH=$(pwd)
          go get github.com/golang/protobuf/protoc-gen-go
          go get github.com/golang/mock/mockgen
          go get golang.org/x/tools/cmd/goimports
          ls -lha ./bin
      - name: Generate stubs and mocks
        run: |
          export PATH=$PATH:../tools/bin/ && mkdir -p proto && mkdir -p mock_proto
          protoc -I ../grpc_defs -I ../grpc_defs/vendor --go_out=plugins=grpc:proto ../grpc_defs/init.proto ../grpc_defs/security.proto
          export GOPATH=$(pwd)/..
          mockgen -package mock_proto -destination mock_proto/mock_initializer.go -source proto/init.pb.go
          mockgen -package mock_proto -destination mock_proto/mock_security.go    -source proto/security.pb.go
          goimports -w ./
          git add -A
          git status
      - name: Commit changes if any
        run: |
          git config --local user.name "Trung Nguyen"
          git config --local user.email "24930+trung@users.noreply.github.com"
          git commit -am "Auto update" || echo
      - name: Push changes if any
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.QUORUMBOT_PAT }}
